-- 添加图表大模型配置
-- 执行前先确认表结构
-- PLATFORM: AI_ECHARTS_MODEL
-- ACCESSKEYID: 模型 ID（如 qwen-plus、codeqwen-turbo），值为 NONE 时使用自动图表

INSERT INTO PRODUCT_APPKEY (PLATFORM, ACCESSKEYID, ACCESSKEYSECRET, CREATED_TIME) 
VALUES ('AI_ECHARTS_MODEL', 'NONE', '', SYSDATE);

-- 验证是否添加成功
SELECT * FROM PRODUCT_APPKEY WHERE PLATFORM = 'AI_ECHARTS_MODEL';

-- 修改模型示例（切换到 qwen-plus）
-- UPDATE PRODUCT_APPKEY SET ACCESSKEYID = 'qwen-plus' WHERE PLATFORM = 'AI_ECHARTS_MODEL';

-- 关闭 AI 图表（使用自动图表）
-- UPDATE PRODUCT_APPKEY SET ACCESSKEYID = 'NONE' WHERE PLATFORM = 'AI_ECHARTS_MODEL';
