-- =====================================================
-- 商品识别优化 - 数据库建表脚本（Oracle）
-- 创建时间：2026-04-12
-- 执行顺序：1
-- =====================================================

-- =====================================================
-- 1. 商品图像特征表
-- =====================================================

CREATE TABLE PRODUCT_IMAGE_FEATURES (
    FEATURE_ID VARCHAR2(36) CONSTRAINT PK_PRODUCT_IMAGE_FEATURES PRIMARY KEY,
    PLUNO VARCHAR2(50) NOT NULL,
    IMAGE_URL VARCHAR2(500),
    OSS_IMAGE_URL VARCHAR2(1000),
    FEATURE_VECTOR BLOB,
    FEATURE_DIMENSION NUMBER DEFAULT 512,
    MODEL_VERSION VARCHAR2(50),
    CREATED_TIME DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(50),
    REMARK VARCHAR2(500)
);

COMMENT ON TABLE PRODUCT_IMAGE_FEATURES IS '商品图像特征表';
COMMENT ON COLUMN PRODUCT_IMAGE_FEATURES.FEATURE_ID IS '特征 ID（UUID）';
COMMENT ON COLUMN PRODUCT_IMAGE_FEATURES.PLUNO IS '商品品号';
COMMENT ON COLUMN PRODUCT_IMAGE_FEATURES.IMAGE_URL IS '图片 URL';
COMMENT ON COLUMN PRODUCT_IMAGE_FEATURES.OSS_IMAGE_URL IS '阿里云 OSS 图片 URL';
COMMENT ON COLUMN PRODUCT_IMAGE_FEATURES.FEATURE_VECTOR IS '特征向量（二进制存储）';
COMMENT ON COLUMN PRODUCT_IMAGE_FEATURES.FEATURE_DIMENSION IS '向量维度（512/1024）';
COMMENT ON COLUMN PRODUCT_IMAGE_FEATURES.MODEL_VERSION IS '模型版本';
COMMENT ON COLUMN PRODUCT_IMAGE_FEATURES.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN PRODUCT_IMAGE_FEATURES.CREATED_BY IS '创建人';
COMMENT ON COLUMN PRODUCT_IMAGE_FEATURES.REMARK IS '备注';

CREATE INDEX IDX_PLUNO ON PRODUCT_IMAGE_FEATURES(PLUNO);
CREATE INDEX IDX_CREATED_TIME ON PRODUCT_IMAGE_FEATURES(CREATED_TIME);
CREATE INDEX IDX_MODEL_VERSION ON PRODUCT_IMAGE_FEATURES(MODEL_VERSION);


-- =====================================================
-- 2. 修改现有表 - PRODUCT_TRAINING_SAMPLES
-- =====================================================

ALTER TABLE PRODUCT_TRAINING_SAMPLES ADD (
    FEATURE_EXTRACTED VARCHAR2(1) DEFAULT 'N',
    FEATURE_ID VARCHAR2(36),
    FEATURE_EXTRACT_TIME DATE
);

COMMENT ON COLUMN PRODUCT_TRAINING_SAMPLES.FEATURE_EXTRACTED IS '是否已提取特征 Y/N';
COMMENT ON COLUMN PRODUCT_TRAINING_SAMPLES.FEATURE_ID IS '关联的特征 ID';
COMMENT ON COLUMN PRODUCT_TRAINING_SAMPLES.FEATURE_EXTRACT_TIME IS '特征提取时间';


-- =====================================================
-- 3. 修改现有表 - PRODUCT_FEATURES
-- =====================================================

ALTER TABLE PRODUCT_FEATURES ADD (
    HAS_IMAGE_FEATURES VARCHAR2(1) DEFAULT 'N',
    IMAGE_FEATURE_COUNT NUMBER DEFAULT 0,
    LAST_FEATURE_UPDATE DATE
);

COMMENT ON COLUMN PRODUCT_FEATURES.HAS_IMAGE_FEATURES IS '是否有图像特征 Y/N';
COMMENT ON COLUMN PRODUCT_FEATURES.IMAGE_FEATURE_COUNT IS '图像特征数量';
COMMENT ON COLUMN PRODUCT_FEATURES.LAST_FEATURE_UPDATE IS '最后特征更新时间';


-- =====================================================
-- 4. 创建视图 - 商品特征统计
-- =====================================================

CREATE OR REPLACE VIEW V_PRODUCT_FEATURE_STATS AS
SELECT 
    pf.PLUNO,
    pf.PRODUCT_NAME,
    pf.CATEGORY,
    COUNT(pif.FEATURE_ID) AS FEATURE_COUNT,
    MAX(pif.CREATED_TIME) AS LAST_UPDATE_TIME,
    pf.HAS_IMAGE_FEATURES,
    pf.IMAGE_FEATURE_COUNT
FROM PRODUCT_FEATURES pf
LEFT JOIN PRODUCT_IMAGE_FEATURES pif ON pf.PLUNO = pif.PLUNO
GROUP BY 
    pf.PLUNO, 
    pf.PRODUCT_NAME, 
    pf.CATEGORY,
    pf.HAS_IMAGE_FEATURES,
    pf.IMAGE_FEATURE_COUNT;

COMMENT ON TABLE V_PRODUCT_FEATURE_STATS IS '商品特征统计视图';


-- =====================================================
-- 5. 初始化数据
-- =====================================================

UPDATE PRODUCT_FEATURES 
SET 
    HAS_IMAGE_FEATURES = 'N',
    IMAGE_FEATURE_COUNT = 0,
    LAST_FEATURE_UPDATE = NULL
WHERE 
    HAS_IMAGE_FEATURES IS NULL;

COMMIT;


-- =====================================================
-- 6. 验证
-- =====================================================

-- 查看表结构
-- DESC PRODUCT_IMAGE_FEATURES;

-- 查看索引
-- SELECT INDEX_NAME, COLUMN_NAME FROM USER_IND_COLUMNS WHERE TABLE_NAME = 'PRODUCT_IMAGE_FEATURES';

-- 查看视图
-- SELECT * FROM V_PRODUCT_FEATURE_STATS WHERE ROWNUM <= 10;
