-- 为 AI_NL_DIALOGUE 表添加图表相关字段
-- 用于保存 AI 生成的图表配置

-- 添加 CHART_TYPE 字段（VARCHAR2(20)）
ALTER TABLE AI_NL_DIALOGUE ADD (CHART_TYPE VARCHAR2(20));

-- 添加 CHART_CONFIG 字段（CLOB，存储 JSON 配置）
ALTER TABLE AI_NL_DIALOGUE ADD (CHART_CONFIG CLOB);

-- 验证字段是否添加成功
SELECT COLUMN_NAME, DATA_TYPE FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'AI_NL_DIALOGUE' AND COLUMN_NAME IN ('CHART_TYPE', 'CHART_CONFIG');
