-- =====================================================
-- 商品识别日志分析查询
-- 创建时间：2026-04-13
-- =====================================================

-- 1. 查看最新 10 条识别记录（包含匹配方式）
SELECT LOG_ID, RECOGNIZED_PLUNO, RECOGNIZED_NAME, MATCH_TYPE, 
       VECTOR_SIMILARITY, CONFIDENCE, CREATED_TIME 
FROM PRODUCT_RECOGNITION_LOGS 
ORDER BY CREATED_TIME DESC 
FETCH FIRST 10 ROWS ONLY;

-- 2. 统计各种匹配方式的数量
SELECT MATCH_TYPE, 
       COUNT(*) AS MATCH_COUNT,
       ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 2) AS PERCENTAGE
FROM PRODUCT_RECOGNITION_LOGS 
WHERE MATCH_TYPE IS NOT NULL
GROUP BY MATCH_TYPE
ORDER BY MATCH_COUNT DESC;

-- 3. 向量匹配的相似度分布
SELECT 
    CASE 
        WHEN VECTOR_SIMILARITY >= 0.95 THEN '0.95-1.00 (极高)'
        WHEN VECTOR_SIMILARITY >= 0.90 THEN '0.90-0.95 (高)'
        WHEN VECTOR_SIMILARITY >= 0.85 THEN '0.85-0.90 (中高)'
        WHEN VECTOR_SIMILARITY >= 0.80 THEN '0.80-0.85 (中)'
        ELSE '<0.80 (低)'
    END AS SIMILARITY_RANGE,
    COUNT(*) AS COUNT
FROM PRODUCT_RECOGNITION_LOGS 
WHERE MATCH_TYPE = 'VECTOR' AND VECTOR_SIMILARITY IS NOT NULL
GROUP BY 
    CASE 
        WHEN VECTOR_SIMILARITY >= 0.95 THEN '0.95-1.00 (极高)'
        WHEN VECTOR_SIMILARITY >= 0.90 THEN '0.90-0.95 (高)'
        WHEN VECTOR_SIMILARITY >= 0.85 THEN '0.85-0.90 (中高)'
        WHEN VECTOR_SIMILARITY >= 0.80 THEN '0.80-0.85 (中)'
        ELSE '<0.80 (低)'
    END
ORDER BY SIMILARITY_RANGE;

-- 4. 平均相似度统计
SELECT 
    MATCH_TYPE,
    COUNT(*) AS COUNT,
    ROUND(AVG(VECTOR_SIMILARITY), 4) AS AVG_SIMILARITY,
    ROUND(MIN(VECTOR_SIMILARITY), 4) AS MIN_SIMILARITY,
    ROUND(MAX(VECTOR_SIMILARITY), 4) AS MAX_SIMILARITY
FROM PRODUCT_RECOGNITION_LOGS 
WHERE MATCH_TYPE = 'VECTOR' AND VECTOR_SIMILARITY IS NOT NULL
GROUP BY MATCH_TYPE;

-- 5. 识别成功率统计（按匹配方式）
SELECT 
    MATCH_TYPE,
    COUNT(*) AS TOTAL_COUNT,
    SUM(CASE WHEN IS_CORRECT = 'Y' THEN 1 ELSE 0 END) AS CORRECT_COUNT,
    ROUND(SUM(CASE WHEN IS_CORRECT = 'Y' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS ACCURACY_RATE
FROM PRODUCT_RECOGNITION_LOGS 
WHERE MATCH_TYPE IS NOT NULL
GROUP BY MATCH_TYPE
ORDER BY ACCURACY_RATE DESC;

-- 6. 查看今天的识别情况
SELECT 
    MATCH_TYPE,
    COUNT(*) AS TODAY_COUNT
FROM PRODUCT_RECOGNITION_LOGS 
WHERE TRUNC(CREATED_TIME) = TRUNC(SYSDATE)
GROUP BY MATCH_TYPE
ORDER BY TODAY_COUNT DESC;

-- =====================================================
-- 使用说明：
-- 1. 查询 1：查看最新识别记录，了解当前匹配情况
-- 2. 查询 2：统计各种匹配方式的占比，评估特征库效果
-- 3. 查询 3：查看向量匹配的相似度分布
-- 4. 查询 4：向量匹配的详细统计
-- 5. 查询 5：各匹配方式的准确率对比
-- 6. 查询 6：今天的识别情况概览
-- =====================================================
