-- 添加角色定义配置（CATEGORY = 'ROLE'）
INSERT INTO AI_PROMPT_REQUIREMENTS (SORT_ORDER, REQUIREMENT, CATEGORY, ENABLED, REMARK, CREATED_TIME) 
VALUES (0, '你是一个专业的 Oracle SQL 专家，请根据以下数据库表结构，将用户的自然语言问题转换为 Oracle SQL 查询。', 'ROLE', 'Y', '角色定义', SYSDATE);

-- 提交
COMMIT;

-- 验证
SELECT SORT_ORDER, REQUIREMENT, CATEGORY, ENABLED 
FROM AI_PROMPT_REQUIREMENTS 
WHERE CATEGORY = 'ROLE';
