-- ============================================
-- 智问对话日志表结构
-- 执行时间：2026-04-14
-- ============================================

-- ============================================
-- 1. 智问对话日志表
-- ============================================
CREATE TABLE AI_NL_QUERY_LOG (
    LOG_ID              VARCHAR2(64) CONSTRAINT PK_AI_NL_QUERY_LOG PRIMARY KEY,
    SESSION_ID          VARCHAR2(64),
    USER_QUESTION       VARCHAR2(2000) NOT NULL,
    GENERATED_SQL       CLOB NOT NULL,
    IS_RETRY            CHAR(1) DEFAULT 'N' CONSTRAINT CK_AI_NL_RETRY CHECK (IS_RETRY IN ('Y', 'N')),
    ORIGINAL_SQL        CLOB,
    FINAL_SQL           CLOB NOT NULL,
    EXEC_STATUS         VARCHAR2(20) NOT NULL,
    ERROR_MESSAGE       VARCHAR2(2000),
    EXEC_TIME_MS        NUMBER,
    RESPONSE_TIME_MS    NUMBER,
    MODEL_NAME          VARCHAR2(100) DEFAULT 'qwen-plus',
    CREATED_TIME        DATE DEFAULT SYSDATE NOT NULL,
    CREATED_BY          VARCHAR2(100)
);

-- 创建索引
CREATE INDEX IDX_AI_NL_QUERY_TIME ON AI_NL_QUERY_LOG(CREATED_TIME);
CREATE INDEX IDX_AI_NL_QUERY_STATUS ON AI_NL_QUERY_LOG(EXEC_STATUS);
CREATE INDEX IDX_AI_NL_QUERY_SESSION ON AI_NL_QUERY_LOG(SESSION_ID);

-- 添加注释
COMMENT ON TABLE AI_NL_QUERY_LOG IS '智问对话日志表';
COMMENT ON COLUMN AI_NL_QUERY_LOG.LOG_ID IS '日志 ID';
COMMENT ON COLUMN AI_NL_QUERY_LOG.SESSION_ID IS '会话 ID（多轮对话追踪）';
COMMENT ON COLUMN AI_NL_QUERY_LOG.USER_QUESTION IS '用户问题';
COMMENT ON COLUMN AI_NL_QUERY_LOG.GENERATED_SQL IS '生成的 SQL';
COMMENT ON COLUMN AI_NL_QUERY_LOG.IS_RETRY IS '是否重试：Y/N';
COMMENT ON COLUMN AI_NL_QUERY_LOG.ORIGINAL_SQL IS '原始 SQL（重试时有值）';
COMMENT ON COLUMN AI_NL_QUERY_LOG.FINAL_SQL IS '最终执行的 SQL';
COMMENT ON COLUMN AI_NL_QUERY_LOG.EXEC_STATUS IS '执行状态：SUCCESS/FAILED';
COMMENT ON COLUMN AI_NL_QUERY_LOG.ERROR_MESSAGE IS '错误信息';
COMMENT ON COLUMN AI_NL_QUERY_LOG.EXEC_TIME_MS IS 'SQL 执行时间（毫秒）';
COMMENT ON COLUMN AI_NL_QUERY_LOG.RESPONSE_TIME_MS IS '总响应时间（毫秒）';
COMMENT ON COLUMN AI_NL_QUERY_LOG.MODEL_NAME IS '使用的模型';
COMMENT ON COLUMN AI_NL_QUERY_LOG.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN AI_NL_QUERY_LOG.CREATED_BY IS '创建人（用户 ID');


-- ============================================
-- 2. 智问会话表
-- ============================================
CREATE TABLE AI_NL_QUERY_SESSION (
    SESSION_ID          VARCHAR2(64) CONSTRAINT PK_AI_NL_QUERY_SESSION PRIMARY KEY,
    USER_ID             VARCHAR2(100),
    START_TIME          DATE DEFAULT SYSDATE NOT NULL,
    END_TIME            DATE,
    QUESTION_COUNT      NUMBER DEFAULT 0,
    SUCCESS_COUNT       NUMBER DEFAULT 0,
    FAILED_COUNT        NUMBER DEFAULT 0,
    LAST_QUESTION       VARCHAR2(2000),
    STATUS              VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_TIME        DATE DEFAULT SYSDATE NOT NULL
);

-- 添加注释
COMMENT ON TABLE AI_NL_QUERY_SESSION IS '智问会话表';
COMMENT ON COLUMN AI_NL_QUERY_SESSION.SESSION_ID IS '会话 ID';
COMMENT ON COLUMN AI_NL_QUERY_SESSION.USER_ID IS '用户 ID';
COMMENT ON COLUMN AI_NL_QUERY_SESSION.START_TIME IS '会话开始时间';
COMMENT ON COLUMN AI_NL_QUERY_SESSION.END_TIME IS '会话结束时间';
COMMENT ON COLUMN AI_NL_QUERY_SESSION.QUESTION_COUNT IS '问题数量';
COMMENT ON COLUMN AI_NL_QUERY_SESSION.SUCCESS_COUNT IS '成功数量';
COMMENT ON COLUMN AI_NL_QUERY_SESSION.FAILED_COUNT IS '失败数量';
COMMENT ON COLUMN AI_NL_QUERY_SESSION.LAST_QUESTION IS '最后一个问题';
COMMENT ON COLUMN AI_NL_QUERY_SESSION.STATUS IS '状态：ACTIVE/CLOSED';
COMMENT ON COLUMN AI_NL_QUERY_SESSION.CREATED_TIME IS '创建时间';


-- ============================================
-- 3. 智问日志统计视图（按天）
-- ============================================
CREATE OR REPLACE VIEW V_AI_NL_QUERY_DAILY_STATS AS
SELECT 
    TRUNC(CREATED_TIME) AS STAT_DATE,
    COUNT(*) AS TOTAL_QUERIES,
    SUM(CASE WHEN EXEC_STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_COUNT,
    SUM(CASE WHEN EXEC_STATUS = 'FAILED' THEN 1 ELSE 0 END) AS FAILED_COUNT,
    ROUND(SUM(CASE WHEN EXEC_STATUS = 'SUCCESS' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS SUCCESS_RATE,
    ROUND(AVG(EXEC_TIME_MS), 2) AS AVG_EXEC_TIME_MS,
    ROUND(AVG(RESPONSE_TIME_MS), 2) AS AVG_RESPONSE_TIME_MS,
    SUM(CASE WHEN IS_RETRY = 'Y' THEN 1 ELSE 0 END) AS RETRY_COUNT
FROM AI_NL_QUERY_LOG
GROUP BY TRUNC(CREATED_TIME)
ORDER BY STAT_DATE DESC;

-- 添加注释
COMMENT ON TABLE V_AI_NL_QUERY_DAILY_STATS IS '智问日志统计视图（按天）';


-- ============================================
-- 4. 智问日志统计视图（按问题类型）
-- ============================================
CREATE OR REPLACE VIEW V_AI_NL_QUERY_QUESTION_STATS AS
SELECT 
    CASE 
        WHEN UPPER(USER_QUESTION) LIKE '%销售额%' THEN '销售查询'
        WHEN UPPER(USER_QUESTION) LIKE '%销量%' THEN '销量查询'
        WHEN UPPER(USER_QUESTION) LIKE '%库存%' THEN '库存查询'
        WHEN UPPER(USER_QUESTION) LIKE '%品类%' THEN '品类分析'
        WHEN UPPER(USER_QUESTION) LIKE '%门店%' THEN '门店分析'
        WHEN UPPER(USER_QUESTION) LIKE '%占比%' THEN '占比分析'
        WHEN UPPER(USER_QUESTION) LIKE '%趋势%' THEN '趋势分析'
        ELSE '其他'
    END AS QUESTION_TYPE,
    COUNT(*) AS TOTAL_QUERIES,
    SUM(CASE WHEN EXEC_STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_COUNT,
    ROUND(SUM(CASE WHEN EXEC_STATUS = 'SUCCESS' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS SUCCESS_RATE,
    ROUND(AVG(EXEC_TIME_MS), 2) AS AVG_EXEC_TIME_MS
FROM AI_NL_QUERY_LOG
GROUP BY 
    CASE 
        WHEN UPPER(USER_QUESTION) LIKE '%销售额%' THEN '销售查询'
        WHEN UPPER(USER_QUESTION) LIKE '%销量%' THEN '销量查询'
        WHEN UPPER(USER_QUESTION) LIKE '%库存%' THEN '库存查询'
        WHEN UPPER(USER_QUESTION) LIKE '%品类%' THEN '品类分析'
        WHEN UPPER(USER_QUESTION) LIKE '%门店%' THEN '门店分析'
        WHEN UPPER(USER_QUESTION) LIKE '%占比%' THEN '占比分析'
        WHEN UPPER(USER_QUESTION) LIKE '%趋势%' THEN '趋势分析'
        ELSE '其他'
    END
ORDER BY TOTAL_QUERIES DESC;

-- 添加注释
COMMENT ON TABLE V_AI_NL_QUERY_QUESTION_STATS IS '智问日志统计视图（按问题类型）';


-- ============================================
-- 5. 提交
-- ============================================
COMMIT;


-- ============================================
-- 6. 验证
-- ============================================
SELECT 'AI_NL_QUERY_LOG' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM AI_NL_QUERY_LOG
UNION ALL
SELECT 'AI_NL_QUERY_SESSION', COUNT(*) FROM AI_NL_QUERY_SESSION;


-- ============================================
-- 执行完成
-- ============================================
