-- ============================================
-- AI 报表设计器 - 数据库表
-- 创建时间：2026-04-19
-- ============================================

-- 1. 报表定义表
CREATE TABLE AI_REPORT_DEF (
    REPORT_ID VARCHAR2(100) CONSTRAINT PK_AI_REPORT_DEF PRIMARY KEY,
    REPORT_NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION CLOB,
    SQL_TEXT CLOB NOT NULL,
    CHART_CONFIG CLOB,
    LAYOUT_CONFIG CLOB,
    VARIABLES_CONFIG CLOB,
    STATUS NUMBER DEFAULT 100,  -- 100:草稿 200:已发布 300:已停用
    CREATED_BY VARCHAR2(100),
    CREATED_TIME DATE DEFAULT SYSDATE,
    UPDATED_TIME DATE,
    MENU_ID VARCHAR2(100)
);

-- 添加表注释
COMMENT ON TABLE AI_REPORT_DEF IS 'AI 报表定义表';
COMMENT ON COLUMN AI_REPORT_DEF.REPORT_ID IS '报表 ID';
COMMENT ON COLUMN AI_REPORT_DEF.REPORT_NAME IS '报表名称';
COMMENT ON COLUMN AI_REPORT_DEF.DESCRIPTION IS '报表描述';
COMMENT ON COLUMN AI_REPORT_DEF.SQL_TEXT IS 'SQL 语句';
COMMENT ON COLUMN AI_REPORT_DEF.CHART_CONFIG IS '图表配置 JSON';
COMMENT ON COLUMN AI_REPORT_DEF.LAYOUT_CONFIG IS '布局配置 JSON';
COMMENT ON COLUMN AI_REPORT_DEF.VARIABLES_CONFIG IS '变量配置 JSON';
COMMENT ON COLUMN AI_REPORT_DEF.STATUS IS '状态：100 草稿 200 已发布 300 已停用';
COMMENT ON COLUMN AI_REPORT_DEF.CREATED_BY IS '创建人';
COMMENT ON COLUMN AI_REPORT_DEF.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN AI_REPORT_DEF.UPDATED_TIME IS '更新时间';
COMMENT ON COLUMN AI_REPORT_DEF.MENU_ID IS '关联菜单 ID';

-- 创建索引
CREATE INDEX IDX_REPORT_NAME ON AI_REPORT_DEF(REPORT_NAME);
CREATE INDEX IDX_REPORT_STATUS ON AI_REPORT_DEF(STATUS);
CREATE INDEX IDX_REPORT_MENU ON AI_REPORT_DEF(MENU_ID);
CREATE INDEX IDX_REPORT_CREATED_BY ON AI_REPORT_DEF(CREATED_BY);

-- 2. 报表菜单表
CREATE TABLE AI_REPORT_MENU (
    MENU_ID VARCHAR2(100) CONSTRAINT PK_AI_REPORT_MENU PRIMARY KEY,
    MENU_NAME VARCHAR2(200) NOT NULL,
    PARENT_ID VARCHAR2(100) DEFAULT '0',
    SORT_ORDER NUMBER DEFAULT 0,
    ICON VARCHAR2(100),
    STATUS NUMBER DEFAULT 100,
    CREATED_TIME DATE DEFAULT SYSDATE,
    CREATED_BY VARCHAR2(100)
);

-- 添加表注释
COMMENT ON TABLE AI_REPORT_MENU IS 'AI 报表菜单表';
COMMENT ON COLUMN AI_REPORT_MENU.MENU_ID IS '菜单 ID';
COMMENT ON COLUMN AI_REPORT_MENU.MENU_NAME IS '菜单名称';
COMMENT ON COLUMN AI_REPORT_MENU.PARENT_ID IS '父菜单 ID';
COMMENT ON COLUMN AI_REPORT_MENU.SORT_ORDER IS '排序';
COMMENT ON COLUMN AI_REPORT_MENU.ICON IS '图标';
COMMENT ON COLUMN AI_REPORT_MENU.STATUS IS '状态：100 启用 200 停用';

-- 创建索引
CREATE INDEX IDX_MENU_PARENT ON AI_REPORT_MENU(PARENT_ID);
CREATE INDEX IDX_MENU_SORT ON AI_REPORT_MENU(SORT_ORDER);

-- 3. 初始化菜单数据
INSERT INTO AI_REPORT_MENU (MENU_ID, MENU_NAME, PARENT_ID, SORT_ORDER, ICON, STATUS, CREATED_BY)
VALUES ('MENU_ROOT', 'AI 报表中心', '0', 1, 'DataBoard', 100, 'system');

INSERT INTO AI_REPORT_MENU (MENU_ID, MENU_NAME, PARENT_ID, SORT_ORDER, ICON, STATUS, CREATED_BY)
VALUES ('MENU_SALES', '销售报表', 'MENU_ROOT', 1, 'DataAnalysis', 100, 'system');

INSERT INTO AI_REPORT_MENU (MENU_ID, MENU_NAME, PARENT_ID, SORT_ORDER, ICON, STATUS, CREATED_BY)
VALUES ('MENU_STOCK', '库存报表', 'MENU_ROOT', 2, 'Box', 100, 'system');

INSERT INTO AI_REPORT_MENU (MENU_ID, MENU_NAME, PARENT_ID, SORT_ORDER, ICON, STATUS, CREATED_BY)
VALUES ('MENU_CUSTOM', '自定义报表', 'MENU_ROOT', 3, 'Setting', 100, 'system');

-- 4. 报表版本历史表（可选）
CREATE TABLE AI_REPORT_VERSION (
    VERSION_ID VARCHAR2(100) CONSTRAINT PK_AI_REPORT_VERSION PRIMARY KEY,
    REPORT_ID VARCHAR2(100) NOT NULL,
    VERSION_NUMBER NUMBER NOT NULL,
    SNAPSHOT_JSON CLOB,
    CHANGE_DESCRIPTION VARCHAR2(500),
    CREATED_BY VARCHAR2(100),
    CREATED_TIME DATE DEFAULT SYSDATE
);

COMMENT ON TABLE AI_REPORT_VERSION IS 'AI 报表版本历史表';
COMMENT ON COLUMN AI_REPORT_VERSION.VERSION_ID IS '版本 ID';
COMMENT ON COLUMN AI_REPORT_VERSION.REPORT_ID IS '报表 ID';
COMMENT ON COLUMN AI_REPORT_VERSION.VERSION_NUMBER IS '版本号';
COMMENT ON COLUMN AI_REPORT_VERSION.SNAPSHOT_JSON IS '配置快照 JSON';
COMMENT ON COLUMN AI_REPORT_VERSION.CHANGE_DESCRIPTION IS '变更说明';

CREATE INDEX IDX_VERSION_REPORT ON AI_REPORT_VERSION(REPORT_ID);

-- 5. 序列（用于生成 ID）
CREATE SEQUENCE SEQ_REPORT_ID START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE SEQ_MENU_ID START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE SEQ_VERSION_ID START WITH 1 INCREMENT BY 1 NOMAXVALUE;

COMMIT;
